Prevent commit-to or cherry-pick-to from being ran when repo has files marked "assumed unchanged".

diff --git a/git-commit-to b/git-commit-to
--- a/git-commit-to
+++ b/git-commit-to
@@ -13,6 +13,11 @@ fi
 branch="$1"
 shift 1
 
+if git is-dirty -a; then
+    echo 'Cannot use this command safely when you have local files marked "assumed unchanged".' >&2
+    exit 2
+fi
+
 # TODO: FIXME: There is a lot that can go wrong here.  Basically, that's not
 # a problem at all in itself, but we need a mechanism to reliably recover back
 # to the starting position.
