Add -l flag to git-cleanup

diff --git a/git-cleanup b/git-cleanup
--- a/git-cleanup
+++ b/git-cleanup
@@ -10,13 +10,16 @@ usage () {
     echo >&2
     echo "Options:" >&2
     echo "-n    Dry-run" >&2
+    echo "-l    Local branches only, don't touch the remotes"
     echo "-h    Show this help" >&2
 }
 
 dryrun=0
-while getopts nh flag; do
+remotes=1
+while getopts nlh flag; do
     case "$flag" in
         n) dryrun=1;;
+        l) remotes=0;;
         h) usage; exit 2;;
     esac
 done
@@ -102,22 +105,24 @@ done
 for remote in origin; do
     safegit remote prune "$remote" >/dev/null 2>/dev/null
 
-    branches_to_remove=""
-    for branch in $(git remote-branches "$remote" | grep -vEe '/(master|develop)$'); do
-        for base in $bases; do
-            if git contains "$base" "$branch"; then
-                if ! git contains "$branch" "$base"; then
-                    branchname=$(echo "$branch" | cut -d/ -f2-)
-                    branches_to_remove="$branches_to_remove $branchname"
-                    break
+    if [ $remotes -eq 1 ]; then
+        branches_to_remove=""
+        for branch in $(git remote-branches "$remote" | grep -vEe '/(master|develop)$'); do
+            for base in $bases; do
+                if git contains "$base" "$branch"; then
+                    if ! git contains "$branch" "$base"; then
+                        branchname=$(echo "$branch" | cut -d/ -f2-)
+                        branches_to_remove="$branches_to_remove $branchname"
+                        break
+                    fi
                 fi
-            fi
+            done
         done
-    done
 
-    if [ -n "$branches_to_remove" ]; then
-        if ! safegit push "$remote" --delete $branches_to_remove; then
-            echo "Errors deleting branches $branches_to_remove from remote '$remote'" >&2
+        if [ -n "$branches_to_remove" ]; then
+            if ! safegit push "$remote" --delete $branches_to_remove; then
+                echo "Errors deleting branches $branches_to_remove from remote '$remote'" >&2
+            fi
         fi
     fi
 done
