Make sha fail a bit more friendly if object does not exist.

diff --git a/git-sha b/git-sha
--- a/git-sha
+++ b/git-sha
@@ -12,4 +12,14 @@ else
     exit 2
 fi
 
-git rev-parse "$object"
+set +e
+output=$(git rev-parse "$object" 2>/dev/null)
+status=$?
+set -e
+if [ $status -ne 0 ]; then
+    echo "Invalid object: '$object'" >&2
+    exit 1
+else
+    echo "$output"
+    exit 0
+fi
